const textWithIdiom = {
  en: {
    title: "Questions",
    score: "Score",
    correct: "Correct",
    incorrect: "Incorrect",
    corrects: "Corrects",
    incorrects: "Incorrects",
    play: "Play",
    language: "Language",
    english: "English",
    spanish: "Spanish",
    restart: "Restart",
    dificulty: "Dificulty",
    easy: "Easy",
    normal: "Normal",
    hard: "Hard",
    extreme: "Extreme",
  },
  es: {
    title: "Preguntas",
    score: "Puntaje",
    correct: "Correcto",
    incorrect: "Incorrecto",
    corrects: "Correctas",
    incorrects: "Incorrectas",
    play: "Jugar",
    language: "Idioma",
    english: "Ingles",
    spanish: "Español",
    restart: "Reiniciar",
    dificulty: "Dificultad",
    easy: "Facil",
    normal: "Normal",
    hard: "Dificil",
    extreme: "Extremo",
  },
};

export default textWithIdiom;
